/**
 * Items that are most likely not a shared expense on a supermarket receipt: hygiene and
 * household goods and pantry staples someone keeps (e.g. shower gel, toilet paper, milk,
 * spices). Used in addition to the AI's guess to put them first for crossing out.
 */
const PERSONAL = new RegExp(
  [
    // hygiene and drugstore
    "dusch",
    "shampoo",
    "spülung",
    "seife",
    "zahnpasta",
    "zahncreme",
    "zahnbürste",
    "deo",
    "rasier",
    "(hand|gesichts|körper|sonnen|tages|nacht)creme",
    "lotion",
    "tampon",
    "binden",
    "windel",
    "wattepads",
    "abschmink",
    "balea",
    "nivea",
    "dove",
    "colgate",
    "elmex",
    "gillette",
    // household
    "klopapier",
    "toilettenpapier",
    "toil\\.?papier",
    "küchenrolle",
    "küchentuch",
    "taschentuch",
    "taschentücher",
    "zewa",
    "hakle",
    "tempo",
    "waschmittel",
    "weichspüler",
    "spülmittel",
    "geschirr",
    "spültab",
    "reiniger",
    "müllbeutel",
    "müllsack",
    "batterie",
    "glühbirne",
    "persil",
    "ariel",
    "frosch",
    "pril",
    "sagrotan",
    // pantry staples
    "(?<!kokos|mandel|hafer|soja)milch(?!schoko|reis|brötchen|schnitte|kaffee)",
    "gewürz(?!gurke)",
    "\\bsalz\\b",
    "(meer|jod|speise)salz",
    "pfeffer(?!beißer|minz)",
    "paprika edels",
    "oregano",
    "basilikum getr",
    "zimt",
    "muskat",
    "brühe",
    "essig",
    "öl\\b",
    "mehl",
    "zucker",
    "kaffee",
    "\\btee\\b",
    "haferflocken",
    "müsli",
  ].join("|"),
  "i",
);

export function looksPersonal(name: string): boolean {
  return PERSONAL.test(name);
}
