import { chromium } from "playwright-core";
import { spawn } from "node:child_process";
const SP = process.argv[2];
const ROOT = new URL("..", import.meta.url).pathname; // Repo-Wurzel (Server läuft aus dist-server/)
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const srv = spawn("node", ["dist-server/index.js"], { cwd: ROOT, env: { ...process.env, PORT: "3268", DATA_DIR: SP + "/data-billdiv" }, stdio: "ignore" });
await wait(1500);
const OK = "ownerkey-1234567890abcdef";
const make = async (equalSplit) => (await (await fetch("http://localhost:3268/api/bills", { method: "POST", headers: { "content-type": "application/json", "x-billsplit-key": OK }, body: JSON.stringify({ name: "Niklas", data: { title: "REWE", date: "2026-10-10", currency: "EUR", equalSplit, items: [{ id: "a", name: "Vanille", qty: 1, total: 100, fullTotal: 199, divisor: 2 }, { id: "b", name: "Milch", qty: 1, total: 119 }], tipPercent: 0, payment: { paypalMe: "nik" } } }) })).json()).id;
const eq = await make(true), own = await make(undefined);
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: "de-DE", hasTouch: true });
await ctx.addInitScript((k) => { localStorage.setItem("billsplit.deviceKey", JSON.stringify(k)); localStorage.setItem("billsplit.profile", JSON.stringify({ name: "Niklas", paypalMe: "nik", paypalEmail: "" })); for (const id of ["x"]) localStorage.setItem("billsplit.tapDemo.x", "1"); }, OK);
const p = await ctx.newPage();
await p.goto(`http://localhost:3268/#/b/${eq}`); await p.waitForSelector(".receipt .rline"); await wait(800);
await p.evaluate((id) => localStorage.setItem(`billsplit.tapDemo.${id}`, "1"), eq);
const line = p.locator('.receipt li[data-item="a"]');
await line.scrollIntoViewIfNeeded();
const d = await line.locator(".rline-divisor").boundingBox();
await p.mouse.click(d.x + d.width / 2, d.y + d.height / 2); await wait(1200);
console.log("equal, tap on /2:", (await line.innerText()).replace(/\n/g, " "), "|", await line.getAttribute("class"));
const b = await line.boundingBox();
await p.mouse.click(b.x + 80, b.y + b.height / 2); await wait(800);
console.log("equal, tap on name:", await line.getAttribute("class"));
await p.goto(`http://localhost:3268/#/b/${own}`); await p.waitForSelector(".receipt .rline"); await wait(800);
const l2 = p.locator('.receipt li[data-item="b"]'); await l2.scrollIntoViewIfNeeded();
const b2 = await l2.boundingBox();
await p.mouse.move(b2.x + 120, b2.y + b2.height / 2); await p.mouse.down(); await wait(700); await p.mouse.up(); await wait(500);
console.log("own mode long press → sheet:", await p.locator(".divisor-sheet").count(), "| pressable:", await l2.getAttribute("class"));
await browser.close(); srv.kill();
