import { chromium } from "playwright-core";
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: "de-DE", permissions: ["clipboard-read", "clipboard-write"] });
const page = await ctx.newPage();
await page.goto("http://localhost:8796/");
await page.locator(".action-card.primary").click();
await page.getByPlaceholder("z. B. Niklas").fill("Niklas");
await page.getByPlaceholder("deinname").fill("niklasb");
await page.getByRole("button", { name: "Weiter zur Kamera" }).click();
await page.waitForTimeout(400);
await page.getByLabel("Bezeichnung").first().fill("Pizza");
await page.getByLabel("Preis gesamt").first().fill("12,40");
await page.getByRole("button", { name: "QR-Code erstellen" }).click();
await page.waitForTimeout(500);
await page.getByRole("button", { name: "Ohne Trinkgeld weiter" }).click();
await page.waitForTimeout(1200);
await page.getByRole("radio", { name: /Anna/ }).click(); await page.waitForTimeout(600);
await page.locator(".rline-main", { hasText: "Pizza" }).click(); await page.waitForTimeout(800);
const [popup] = await Promise.all([ctx.waitForEvent("page"), page.locator(".btn-paypal").click()]);
console.log("opened:", popup.url());
await page.waitForTimeout(500);
console.log("clipboard:", await page.evaluate(() => navigator.clipboard.readText()));
console.log("note:", await page.locator(".paybar-note").allInnerTexts());
await browser.close();
