import { chromium } from "playwright-core";
const SP = process.argv[2];
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, locale: "de-DE" });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:8794/");
await page.locator(".action-card.primary").click();
await page.getByPlaceholder("z. B. Niklas").fill("Niklas");
await page.getByPlaceholder("deinname").fill("niklasb");
await page.getByRole("button", { name: "Weiter zur Kamera" }).click();
await page.waitForTimeout(400);
await page.getByPlaceholder("z. B. Trattoria Da Mario").fill("Bar");
await page.getByLabel("Anzahl").first().fill("3");
await page.getByLabel("Bezeichnung").first().fill("Bier");
await page.getByLabel("Preis gesamt").first().fill("12,00");
await page.getByRole("button", { name: "QR-Code erstellen" }).click();
await page.waitForTimeout(500);
await page.getByRole("button", { name: "Ohne Trinkgeld weiter" }).click();
await page.waitForTimeout(1500);
await page.getByRole("radio", { name: /Anna/ }).click();
await page.waitForTimeout(800);
await page.locator(".rline-main", { hasText: "Bier" }).click();
await page.waitForTimeout(800);
await page.getByRole("radio", { name: /Ben/ }).click();
await page.waitForTimeout(800);
await page.locator(".rline-main", { hasText: "Bier" }).click();
await page.waitForTimeout(200);
for (let i = 0; i < 3; i++) { const b = page.getByRole("button", { name: "Eins mehr" }); if (await b.isEnabled()) await b.click(); await page.waitForTimeout(150); }
await page.waitForTimeout(800);
console.log("ben stepper:", await page.locator(".rline-stepper span").innerText(), "| plus enabled:", await page.getByRole("button", { name: "Eins mehr" }).isEnabled());
console.log("claims:", (await page.locator(".rline-claims").innerText()).replace(/\n+/g, " | "));
await page.locator(".receipt-lines").screenshot({ path: `${SP}/shots/limit-ben.png` });
await page.getByRole("radio", { name: /Niklas|Du|Ich/ }).first().click().catch(() => {});
await page.waitForTimeout(800);
console.log("owner tick disabled:", await page.locator(".rline-main", { hasText: "Bier" }).isDisabled());
console.log("errors:", errors);
await browser.close();
