import { chromium } from "playwright-core";
const SP = process.argv[2];
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, locale: "de-DE", permissions: ["clipboard-read", "clipboard-write"] });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:8801/");
await page.locator(".action-card.primary").click();
await page.getByPlaceholder("z. B. Niklas").fill("Niklas");
await page.getByPlaceholder("deinname").fill("niklasb");
await page.getByRole("button", { name: "Weiter zur Kamera" }).click();
await page.waitForTimeout(400);
await page.getByLabel("Bezeichnung").first().fill("Pizza");
await page.getByLabel("Preis gesamt").first().fill("12,40");
await page.getByRole("button", { name: "QR-Code erstellen" }).click();
await page.waitForTimeout(500);
await page.getByRole("button", { name: "Ohne Trinkgeld weiter" }).click();
await page.waitForTimeout(1200);
await page.getByRole("radio", { name: /Anna/ }).click(); await page.waitForTimeout(600);
await page.locator(".rline-main", { hasText: "Pizza" }).click(); await page.waitForTimeout(800);
await page.locator(".btn-paypal").click(); await page.waitForTimeout(300);
const [popup] = await Promise.all([ctx.waitForEvent("page"), page.locator(".btn-paypal").click()]);
await popup.close(); await page.waitForTimeout(800);
console.log("buttons:", await page.locator(".paybar .btn").allInnerTexts());
await page.getByRole("button", { name: "Als bezahlt markieren" }).click(); await page.waitForTimeout(700);
console.log("after mark:", (await page.locator(".paybar").innerText()).replace(/\n+/g, " | "));
await page.locator(".paybar").screenshot({ path: `${SP}/shots/markpaid.png` });
await page.getByRole("radio", { name: /^(Du|Ich|Niklas)/ }).first().click(); await page.waitForTimeout(700);
console.log("owner sees:", await page.locator(".debtor-status").first().innerText());
console.log("errors:", errors);
await browser.close();
