import { chromium } from "playwright-core";
import { spawn } from "node:child_process";
const SP = process.argv[2];
const ROOT = new URL("..", import.meta.url).pathname; // Repo-Wurzel (Server läuft aus dist-server/)
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const srv = spawn("node", ["dist-server/index.js"], { cwd: ROOT, env: { ...process.env, PORT: "3251", DATA_DIR: SP + "/data-partial" }, stdio: "ignore" });
await wait(1500);
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, locale: "de-DE", hasTouch: true });
await ctx.addInitScript(() => localStorage.setItem("billsplit.profile", JSON.stringify({ name: "Katia", paypalMe: "katia", paypalEmail: "" })));
const page = await ctx.newPage();
await page.route("**/api/parse-receipt", (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ merchant: "Lidl", date: "2026-10-10", currency: "EUR", items: [{ name: "Gehackte Tomaten", qty: 1, total: 59 }, { name: "Kichererbsen", qty: 3, total: 177 }, { name: "Pringles", qty: 1, total: 279 }], total: 515, tip: null, fees: [], delivery: false, supermarket: true, engine: "ai" }) }));
await page.goto("http://localhost:3251/");
await page.locator(".action-card.primary input[type=file]").setInputFiles(`${SP}/shots/app-receipt.png`);
await page.waitForSelector(".sheet h2", { timeout: 15000 });
await page.getByRole("button", { name: "Manches nicht" }).click(); await wait(900);
const line = page.locator('.scribble li[data-item]', { hasText: "Kichererbsen" });
const tapLine = async () => { const b = await line.boundingBox(); await page.touchscreen.tap(b.x + 120, b.y + b.height / 2); await wait(500); };
const show = async (label) => console.log(label, "|", (await line.innerText()).replace(/\n/g, " "), "| class:", await line.getAttribute("class"), "| notice:", await page.locator(".scribble-notice").textContent().catch(() => ""), "| sum:", await page.locator(".scribble-sum").innerText());
await tapLine(); await show("1 tap");
await line.screenshot({ path: `${SP}/shots/partial-1.png` });
await tapLine(); await show("2 taps");
await tapLine(); await show("3 taps");
await tapLine(); await show("4 taps");
await tapLine(); await show("5 taps (1 struck)");
await page.locator(".scribble-foot").getByRole("button", { name: "Rechnung erstellen" }).click();
await page.waitForSelector(".receipt .rline", { timeout: 10000 }); await wait(1200);
console.log("bill line:", (await page.locator('.receipt .rline', { hasText: "Kichererbsen" }).innerText()).replace(/\n/g, " "));
await browser.close(); srv.kill();
