import { chromium } from "playwright-core";
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, locale: "de-DE" });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:8793/");
await page.locator(".action-card.primary").click();
await page.getByPlaceholder("z. B. Niklas").fill("Niklas");
await page.getByLabel(/E-Mail/i).first().fill("niklas@web.de");
await page.getByRole("button", { name: "Weiter zur Kamera" }).click();
await page.waitForTimeout(400);
await page.getByLabel("Bezeichnung").first().fill("Bier");
await page.getByLabel("Preis gesamt").first().fill("4,00");
await page.getByRole("button", { name: "QR-Code erstellen" }).click();
await page.waitForTimeout(500);
await page.getByRole("button", { name: "Ohne Trinkgeld weiter" }).click();
await page.waitForTimeout(1200);
await page.getByRole("radio", { name: /Anna/ }).click();
await page.waitForTimeout(600);
await page.locator(".rline-main", { hasText: "Bier" }).click();
await page.waitForTimeout(800);
console.log("before:", await page.locator(".btn-paypal").innerText(), await page.locator(".btn-paypal").getAttribute("href"));
const billHash = await page.evaluate(() => location.hash);
// payer adds PayPal.Me to the profile afterwards
await page.evaluate(() => { const p = JSON.parse(localStorage.getItem("billsplit.profile")); p.paypalMe = "niklasb"; localStorage.setItem("billsplit.profile", JSON.stringify(p)); });
await page.getByRole("radio", { name: /^(Du|Ich|Niklas)/ }).first().click();
await page.waitForTimeout(300);
await page.reload();
await page.waitForTimeout(400);
console.log("hash after reload:", await page.evaluate(() => location.hash), await page.locator("h2, .receipt").count());
await page.getByRole("button", { name: /Bar|Rechnung/ }).first().click().catch(() => {});
await page.waitForTimeout(1500);
await page.getByRole("radio", { name: /Anna/ }).click();
await page.waitForTimeout(800);
console.log("after:", await page.locator(".btn-paypal").innerText(), await page.locator(".btn-paypal").getAttribute("href"));
console.log("errors:", errors, billHash);
await browser.close();
