import { chromium } from "playwright-core";
const SP = process.argv[2];
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, locale: "de-DE" });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:8794/");
await page.locator(".action-card.primary").click();
await page.getByPlaceholder("z. B. Niklas").fill("Niklas");
await page.getByPlaceholder("deinname").fill("niklasb");
await page.getByRole("button", { name: "Weiter zur Kamera" }).click();
await page.waitForTimeout(400);
await page.getByLabel("Anzahl").first().fill("3");
await page.getByLabel("Bezeichnung").first().fill("Bier");
await page.getByLabel("Preis gesamt").first().fill("12,00");
await page.getByRole("button", { name: "QR-Code erstellen" }).click();
await page.waitForTimeout(500);
await page.getByRole("button", { name: "Ohne Trinkgeld weiter" }).click();
await page.waitForTimeout(1500);
const bier = () => page.locator(".rline-main", { hasText: "Bier" });
const claims = async () => (await page.locator(".rline-claims").innerText()).replace(/\n+/g, " | ");
await bier().click(); await page.waitForTimeout(700);
await page.getByRole("radio", { name: /Anna/ }).click(); await page.waitForTimeout(700);
await bier().click(); await page.waitForTimeout(700);
await page.getByRole("radio", { name: /Ben/ }).click(); await page.waitForTimeout(700);
await bier().click(); await page.waitForTimeout(700);
console.log("all taken:", await claims());
await page.getByRole("radio", { name: /Anna/ }).click(); await page.waitForTimeout(700);
await page.getByRole("button", { name: "Ein Stück mit Ben teilen" }).click(); await page.waitForTimeout(900);
console.log("anna shares ben:", await claims());
console.log("anna paybar:", (await page.locator(".paybar-total").innerText()));
await page.locator(".receipt-lines").screenshot({ path: `${SP}/shots/share-anna.png` });
await page.getByRole("radio", { name: /Ben/ }).click(); await page.waitForTimeout(700);
console.log("ben paybar:", (await page.locator(".paybar-total").innerText()));
console.log("ben view:", await claims(), "| line class:", await page.locator(".rline").first().getAttribute("class"));
await page.locator(".receipt-lines").screenshot({ path: `${SP}/shots/share-ben.png` });
await page.getByRole("radio", { name: /^(Du|Ich|Niklas)/ }).first().click(); await page.waitForTimeout(700);
console.log("owner view:", await claims());
await page.locator(".receipt-lines").screenshot({ path: `${SP}/shots/share-owner.png` });
await page.getByRole("radio", { name: /Anna/ }).click(); await page.waitForTimeout(700);
await page.getByRole("button", { name: "Nicht mehr mit Ben teilen" }).click(); await page.waitForTimeout(900);
console.log("anna stops:", await claims());
console.log("errors:", errors);
await browser.close();
