import { chromium } from "playwright-core";
const SP = process.argv[2];
const out = (n) => `${SP}/shots/demo/${n}.png`;
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, locale: "de-DE" });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:8790/");
await page.getByRole("button", { name: /Beispielrechnung ansehen/ }).click();
await page.getByPlaceholder("z. B. Niklas").fill("Niklas");
await page.getByPlaceholder("deinname").fill("niklasb");
await page.getByRole("button", { name: "Weiter zur Beispielrechnung" }).click();
await page.waitForTimeout(1200);
const panel = page.locator(".tip-split-panel");
console.log("before:", (await panel.innerText()).replace(/\n+/g, " | "));
console.log("receipt tip:", (await page.locator(".receipt-sums").innerText()).replace(/\n+/g, " | "));
await page.getByRole("button", { name: "Eine Person mehr" }).click();
await page.waitForTimeout(600);
console.log("after +1:", (await panel.innerText()).replace(/\n+/g, " | "));
await page.locator(".owner-panel").screenshot({ path: out("20-owner-split") });
console.log("ownerbar:", (await page.locator(".ownerbar").innerText()).replace(/\n+/g, " | "));
await page.getByRole("radio", { name: /Anna/ }).click();
await page.waitForTimeout(600);
console.log("anna paybar:", (await page.locator(".paybar").innerText()).replace(/\n+/g, " | "));
console.log("anna receipt tip:", (await page.locator(".receipt-sums").innerText()).replace(/\n+/g, " | "));
// Editor: tip sheet with persons field
await page.getByRole("radio", { name: /Niklas/ }).click();
await page.waitForTimeout(400);
await page.locator(".topbar .icon-btn").first().click();
await page.waitForTimeout(400);
await page.evaluate(() => { const i = document.querySelector('.action-card.primary input'); });
console.log("errors:", errors);
await browser.close();
