import { chromium } from "playwright-core";
const SP = process.argv[2];
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, locale: "de-DE" });
const page = await ctx.newPage();
await page.goto("http://localhost:8791/");
await page.locator(".action-card.primary").click();
await page.getByPlaceholder("z. B. Niklas").fill("Niklas");
await page.getByPlaceholder("deinname").fill("niklasb");
await page.getByRole("button", { name: "Weiter zur Kamera" }).click();
await page.waitForTimeout(400);
await page.getByPlaceholder("z. B. Trattoria Da Mario").fill("Takumi");
await page.getByLabel("Anzahl").first().fill("2");
await page.getByLabel("Bezeichnung").first().fill("Karaage Tan Tan Men mit extra Ei und Nori");
await page.getByLabel("Preis gesamt").first().fill("37,60");
await page.getByRole("button", { name: "+ Position hinzufügen" }).click();
await page.getByLabel("Bezeichnung").nth(1).fill("Takoyaki (4 St.)");
await page.getByLabel("Preis gesamt").nth(1).fill("6,50");
await page.getByRole("button", { name: "QR-Code erstellen" }).click();
await page.waitForTimeout(500);
await page.getByRole("button", { name: "Ohne Trinkgeld weiter" }).click();
await page.waitForTimeout(1500);
await page.locator(".rline-main", { hasText: "Karaage" }).click();
await page.waitForTimeout(300);
await page.getByRole("button", { name: "Eins mehr" }).click();
await page.locator(".rline-main", { hasText: "Takoyaki" }).click();
await page.waitForTimeout(1000);
await page.locator(".receipt-lines").screenshot({ path: `${SP}/shots/strike.png` });
await browser.close();
