import { chromium } from "playwright-core";
import { spawn } from "node:child_process";
const ROOT = new URL("..", import.meta.url).pathname; // Repo-Wurzel (Server läuft aus dist-server/)
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const srv = spawn("node", ["dist-server/index.js"], { cwd: ROOT, env: { ...process.env, PORT: "3196", DATA_DIR: process.argv[2] + "/data-tick", RAILWAY_GIT_COMMIT_SHA: "abc1234" }, stdio: "inherit" });
await wait(1500);
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: "de-DE" });
await ctx.addInitScript(() => localStorage.setItem("billsplit.profile", JSON.stringify({ name: "Niklas", paypalMe: "niklasb", paypalEmail: "" })));
const page = await ctx.newPage();
page.on("pageerror", (e) => console.log("pageerror", e.message));
page.on("response", (r) => { if (r.url().includes("/claims")) r.text().then((t) => console.log("claims resp", r.status(), t.slice(0, 300))); });
await page.goto("http://localhost:3196/#/new");
await wait(800);
await page.getByLabel("Anzahl").first().fill("3");
await page.getByLabel("Bezeichnung").first().fill("Bier");
await page.getByLabel("Preis gesamt").first().fill("12,00");
await page.getByRole("button", { name: "QR-Code erstellen" }).click();
await wait(500);
await page.getByRole("button", { name: "Ohne Trinkgeld weiter" }).click();
await wait(1500);
await page.locator(".rline-main", { hasText: "Bier" }).click();
await wait(300);
console.log("after 300ms:", await page.locator(".rline").first().getAttribute("class"));
await wait(2000);
console.log("after 2s:", await page.locator(".rline").first().getAttribute("class"));
// second device joins and ticks
const ctx2 = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: "de-DE" });
await ctx2.addInitScript(() => localStorage.setItem("billsplit.profile", JSON.stringify({ name: "Anna", paypalMe: "", paypalEmail: "" })));
const p2 = await ctx2.newPage();
p2.on("pageerror", (e) => console.log("pageerror2", e.message));
await p2.goto(page.url());
await wait(1500);
await p2.locator(".rline-main", { hasText: "Bier" }).click();
await wait(2000);
console.log("anna:", await p2.locator(".rline").first().getAttribute("class"), (await p2.locator(".rline-claims").innerText()).replace(/\n/g, " "));
console.log("owner:", (await page.locator(".rline-claims").innerText()).replace(/\n/g, " "));
await browser.close();
srv.kill();
