import { chromium } from "playwright-core";
import { spawn } from "node:child_process";
const SP = process.argv[2];
const ROOT = new URL("..", import.meta.url).pathname; // Repo-Wurzel (Server läuft aus dist-server/)
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const srv = spawn("node", ["dist-server/index.js"], { cwd: ROOT, env: { ...process.env, PORT: "3257", DATA_DIR: SP + "/data-tip" }, stdio: "ignore" });
await wait(1500);
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, locale: "de-DE", hasTouch: true });
await ctx.addInitScript(() => localStorage.setItem("billsplit.profile", JSON.stringify({ name: "Niklas", paypalMe: "nik", paypalEmail: "" })));
const page = await ctx.newPage();
await page.route("**/api/parse-receipt", (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ merchant: "REWE City", date: "2017-06-23", currency: "EUR", items: [{ name: "Spruehsahne 30%", qty: 2, total: 198 }, { name: "Vanille", qty: 1, total: 199 }, { name: "Milchschokostr", qty: 1, total: 99 }, { name: "Trinkhalme", qty: 1, total: 149 }], total: 655, tip: null, fees: [{ name: "Liefergebühr", amount: 299 }], delivery: true, supermarket: false, engine: "ai" }) }));
await page.goto("http://localhost:3257/");
await page.locator(".action-card.primary input[type=file]").setInputFiles(`${SP}/shots/app-receipt.png`);
await wait(3500);
await wait(800);
await page.screenshot({ path: `${SP}/shots/tip-editor.png` });
const btn = page.getByRole("button", { name: /Rechnung erstellen|Weiter/ }).first(); await btn.click(); await wait(800);
await page.screenshot({ path: `${SP}/shots/tip-after-click.png` }); await page.locator(".sheet").getByRole("radio", { name: "absolut" }).click();
await page.locator(".sheet").getByLabel("Trinkgeld als Betrag").fill("3");
await wait(300);
console.log((await page.locator(".sheet .tip-preview").innerText()).replace(/\n/g, " | "));
await page.locator(".sheet").screenshot({ path: `${SP}/shots/tip-sheet.png` });
await page.locator(".sheet").getByRole("button", { name: "Rechnung erstellen" }).click();
await page.waitForSelector(".receipt .rline", { timeout: 10000 }); await wait(800);
console.log("bill:", (await page.locator(".receipt-sums").innerText()).replace(/\n/g, " | "));
await browser.close(); srv.kill();
