import { chromium } from "playwright-core";
const SP = process.argv[2];
const out = (n) => `${SP}/shots/demo/${n}.png`;
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, locale: "de-DE" });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:8790/");
await page.locator(".action-card.primary").click();
await page.getByPlaceholder("z. B. Niklas").fill("Niklas");
await page.getByPlaceholder("deinname").fill("niklasb");
await page.getByRole("button", { name: "Weiter zur Kamera" }).click();
await page.waitForTimeout(400);
await page.getByPlaceholder("z. B. Trattoria Da Mario").fill("Pizzeria Roma");
await page.getByLabel("Bezeichnung").first().fill("Pizza Diavola");
await page.getByLabel("Preis gesamt").first().fill("12,00");
await page.getByRole("button", { name: "+ Position hinzufügen" }).click();
await page.getByLabel("Anzahl").nth(1).fill("2");
await page.getByLabel("Bezeichnung").nth(1).fill("Aperol Spritz");
await page.getByLabel("Preis gesamt").nth(1).fill("14,00");
await page.getByRole("button", { name: "QR-Code erstellen" }).click();
await page.waitForTimeout(500);
await page.screenshot({ path: out("10-tip-sheet") });
await page.locator(".sheet").getByRole("radio", { name: "als Endbetrag" }).click();
await page.locator(".sheet").getByLabel("Endbetrag inklusive Trinkgeld").fill("30,00");
await page.waitForTimeout(200);
console.log("preview:", (await page.locator(".sheet .tip-preview").innerText()).replace(/\n+/g, " | "));
await page.screenshot({ path: out("11-tip-amount") });
await page.locator(".sheet").getByRole("button", { name: "QR-Code erstellen" }).click();
await page.waitForTimeout(1200);
console.log("receipt sums:", (await page.locator(".receipt-sums").innerText()).replace(/\n+/g, " | "));
await page.getByRole("radio", { name: /Anna/ }).click();
await page.waitForTimeout(600);
await page.locator(".rline-main", { hasText: "Aperol" }).click();
await page.waitForTimeout(800);
console.log("anna paybar:", (await page.locator(".paybar").innerText()).replace(/\n+/g, " | "));
console.log("anna href:", await page.locator(".btn-paypal").getAttribute("href"));
await page.screenshot({ path: out("12-anna-tip") });
console.log("errors:", errors);
await browser.close();
