import { chromium } from "playwright-core";
import { spawn } from "node:child_process";
const SP = process.argv[2];
const ROOT = new URL("..", import.meta.url).pathname; // Repo-Wurzel (Server läuft aus dist-server/)
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const srv = spawn("node", ["dist-server/index.js"], { cwd: ROOT, env: { ...process.env, PORT: "3249", DATA_DIR: SP + "/data-toggle" }, stdio: "ignore" });
await wait(1500);
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, locale: "de-DE", hasTouch: true });
await ctx.addInitScript(() => localStorage.setItem("billsplit.profile", JSON.stringify({ name: "Katia", paypalMe: "katia", paypalEmail: "" })));
const page = await ctx.newPage();
await page.route("**/api/parse-receipt", (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ merchant: "REWE City", date: "2017-06-23", currency: "EUR", items: [{ name: "Spruehsahne 30%", qty: 2, total: 198 }, { name: "Vanille", qty: 1, total: 199 }, { name: "Milchschokostr", qty: 1, total: 99 }, { name: "Trinkhalme", qty: 1, total: 149 }], total: 645, tip: null, fees: [], delivery: false, supermarket: true, engine: "ai" }) }));
await page.goto("http://localhost:3249/");
await page.locator(".action-card.primary input[type=file]").setInputFiles(`${SP}/shots/app-receipt.png`);
await page.waitForSelector(".sheet h2", { timeout: 15000 });
await page.getByRole("button", { name: "Manches nicht" }).click(); await wait(900);
await page.screenshot({ path: `${SP}/shots/toggle-on.png` });
await page.getByRole("switch", { name: /Gleichverteilung/ }).click(); await wait(400);
const line = page.locator('.scribble li[data-item]').first(); const b = await line.boundingBox();
await page.touchscreen.tap(b.x + 80, b.y + b.height / 2); await wait(800);
await page.screenshot({ path: `${SP}/shots/toggle-off.png` });
await page.locator(".scribble-foot").getByRole("button", { name: "Rechnung erstellen" }).click();
await page.waitForSelector(".receipt .rline", { timeout: 10000 }); await wait(1200);
console.log("bill equal lines:", await page.locator(".receipt .rline.equal").count(), "| ticks visible:", await page.locator(".receipt .rline:not(.excluded) .tick").count(), "| excluded:", await page.locator(".receipt .rline.excluded").allTextContents());
await browser.close(); srv.kill();
