import { chromium } from "playwright-core";
import { spawn } from "node:child_process";
const SP = process.argv[2];
const ROOT = new URL("..", import.meta.url).pathname; // Repo-Wurzel (Server läuft aus dist-server/)
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const srv = spawn("node", ["dist-server/index.js"], { cwd: ROOT, env: { ...process.env, PORT: "3259", DATA_DIR: SP + "/data-undiv" }, stdio: "ignore" });
await wait(1500);
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, locale: "de-DE", hasTouch: true });
await ctx.addInitScript(() => localStorage.setItem("billsplit.profile", JSON.stringify({ name: "Niklas", paypalMe: "nik", paypalEmail: "" })));
const page = await ctx.newPage();
await page.route("**/api/parse-receipt", (route) => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ merchant: "REWE City", date: "2017-06-23", currency: "EUR", items: [{ name: "Spruehsahne 30%", qty: 2, total: 198 }, { name: "Vanille", qty: 1, total: 199 }, { name: "Milchschokostr", qty: 1, total: 99 }, { name: "Trinkhalme", qty: 1, total: 149 }], total: 655, tip: null, fees: [{ name: "KL.PAPIERTASCHE", amount: 10 }], delivery: false, supermarket: true, engine: "ai" }) }));
await page.goto("http://localhost:3259/");
await page.locator(".action-card.primary input[type=file]").setInputFiles(`${SP}/shots/app-receipt.png`);
await page.waitForSelector(".sheet h2", { timeout: 15000 });
await page.getByRole("button", { name: "Manches nicht" }).click(); await wait(900);
const t0 = Date.now();
const sums = () => page.locator(".scribble .receipt-sums").innerText().then((t) => t.replace(/\n/g, " | "));
// Long press on "Vanille"
const line = page.locator('.scribble li[data-item]').filter({ hasText: "Vanille" });
const box = await line.boundingBox();
await page.mouse.move(box.x + 60, box.y + box.height / 2);
await page.mouse.down(); await wait(700); await page.mouse.up(); await wait(400);
console.log("sheet:", await page.locator(".divisor-sheet h2").innerText(), "select:", await page.locator(".divisor-sheet h2").evaluate((el) => getComputedStyle(el).userSelect), await page.locator(".scribble .rline-name").first().evaluate((el) => getComputedStyle(el).userSelect));
await page.getByRole("button", { name: "Kleinerer Teil" }).click();
console.log("result:", await page.locator(".divisor-result").innerText());
await page.screenshot({ path: `${SP}/shots/hold-sheet.png` });
await page.getByRole("button", { name: "Übernehmen" }).click(); await wait(500);
console.log("line:", (await line.innerText()).replace(/\n/g, " "), "| struck?", await line.getAttribute("class"));
console.log("sums after:", await sums());
const d = await line.locator(".rline-divisor").boundingBox();
await page.mouse.click(d.x + d.width / 2 + 3, d.y + d.height / 2); await wait(600);
console.log("after tap on /2:", (await line.innerText()).replace(/\n/g, " "), "|", await line.getAttribute("class"), "|", await page.locator(".scribble-notice").innerText().catch(() => ""));
const b2 = await line.boundingBox();
await page.mouse.click(b2.x + 30, b2.y + b2.height / 2); await wait(600);
console.log("after tap on name:", await line.getAttribute("class"));
await browser.close(); srv.kill();
