import { chromium } from "playwright-core";
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: "de-DE" });
await ctx.addInitScript(() => localStorage.setItem("billsplit.profile", JSON.stringify({ name: "Niklas", paypalMe: "niklasb", paypalEmail: "" })));
const page = await ctx.newPage();
await page.goto("http://localhost:8791/");
await page.getByRole("button", { name: /Beispielrechnung ansehen/ }).click();
await page.waitForTimeout(800);
await page.getByRole("radio", { name: /Ben/ }).click();
await page.waitForTimeout(500);
const wasser = page.locator(".rline", { hasText: "Wasser" });
await wasser.locator(".rline-main").click();
await page.waitForTimeout(500);
console.log("nach Anhaken:", await wasser.locator(".rline-stepper span").innerText());
await wasser.getByRole("button", { name: "Eins mehr" }).click();
await page.waitForTimeout(400);
console.log("nach +:", await wasser.locator(".rline-stepper span").innerText());
await wasser.locator(".rline-main").click();
await page.waitForTimeout(400);
console.log("nach erneutem Antippen (abwählen):", await wasser.locator(".rline-stepper").count() === 0 ? "abgewählt" : "noch gewählt");
await browser.close();
